Vagrant.configure("2") do |config|
  config.vm.box = "alanjponte"
  config.vm.hostname = "alanjponte"
  # Set the display name
  config.vm.define "vagrantWebsite" do |vagrantWebsite| end
  config.vm.network :private_network, ip: "192.168.0.42"
end
